### PR TITLE
Allow manual override of max temp via env var

### PR DESCRIPTION
**Pull request by sjdaws**
This change allows `MAXTEMP` to be specified as a docker environment variable.

### CODE REVIEW

**Comment by tigerblue77** [comment]
Reviewed and validated.

**Review by tigerblue77 — CHANGES_REQUESTED** [review]
You forgot to change :
- startup.sh script to :
```bash
echo $IDRAC_HOST >> /host.txt
echo $IDRAC_USER >> /user.txt
echo $IDRAC_PW >> /pw.txt
echo $FANSPEED >> /fanspeed.txt
echo $MAXTEMP >> /maxtemp.txt

echo "Host: `cat /host.txt`"
echo "User: `cat /user.txt`"
echo "PW: `cat /pw.txt`"
echo "Fan speed `cat /fanspeed.txt`"
echo "Max temp `cat /maxtemp.txt`"
```
- check-temp.sh script to :
```bash
IPMIHOST=`cat /host.txt`
IPMIUSER=`cat /user.txt`
IPMIPW=`cat /pw.txt`
FANSPEED=`cat /fanspeed.txt`
MAXTEMP=`cat /maxtemp.txt`
MAXTEMP=${MAXTEMP:-32}

TEMP=$(ipmitool -I lanplus -H $IPMIHOST -U $IPMIUSER -P $IPMIPW sdr type temperature |grep Inlet |grep degrees |grep -Po '\d{2}' | tail -1)

echo "Current Temp is $TEMP C"
if [ $TEMP -gt $MAXTEMP ];
then
  echo "Temp is too high. Activating dynamic fan control"
  ipmitool -I lanplus -H $IPMIHOST -U $IPMIUSER -P $IPMIPW raw 0x30 0x30 0x01 0x01
else
  echo "Temp is OK. Using manual fan control"
  ipmitool -I lanplus -H $IPMIHOST -U $IPMIUSER -P $IPMIPW raw 0x30 0x30 0x01 0x00
  ipmitool -I lanplus -H $IPMIHOST -U $IPMIUSER -P $IPMIPW raw 0x30 0x30 0x02 0xff $FANSPEED
fi
```

**Comment by sjdaws** [comment]
I added it to `startup.sh` and changed it to read in `check-temp.sh`

**Comment by tigerblue77** [comment]
Seems OK to me. Don't hesitate to check my fork if you use this container and to propose a merge request on it :)

**Review by alombardo4 — APPROVED** [review]

**Pull request merged**
