### PR TITLE
Allow decimal values for the fan speed

### PR DESCRIPTION
**Pull request by tigerblue77**

### CODE REVIEW

**Review by alombardo4 — APPROVED** [review]

**Comment by tigerblue77** [comment]
Thanks for merging, did you test it ?

**Comment by alombardo4** [comment]
Yep, it seems to work locally. Thanks for the contribution! I'll get it published to docker hub shortly.

**Comment by alombardo4** [comment]
As an FYI, I've personally moved to using https://github.com/alombardo4/idrac-fan-control-nodejs. It handles things like container restarts much more gracefully (and was moved to GHCR instead of Docker hub).

**Comment by alombardo4** [comment]
https://github.com/alombardo4/idrac-fan-control-docker/commit/ade0b854d61db6e9e715f691ed705dd487a56180 was just published as `alombardo4/idrac-fan-control:latest`

**Comment by tigerblue77** [comment]
> I've personally moved to using https://github.com/alombardo4/idrac-fan-control-nodejs

Thanks for the information but I don't really know nodeJS and don't really want to learn another language to contribute...
I made #7 which handles Docker container restart/stop.

**Comment by tigerblue77** [comment]
> was moved to GHCR instead of Docker hub

Why ? What is/are the advantage(s) ?

**Pull request merged**
